apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web
  labels:
    app: apache-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-web
  template:
    metadata:
      labels:
        app: apache-web
    spec:
      containers:
        - name: apache-web
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: web-content
          configMap:
            name: apache-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-content
data:
  index.html: |
    <html>
      <head><title>Apache Test</title></head>
      <body>
        <h1>Hello from Apache Webserver on GKE Autopilot via Fleet!</h1>
      </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: apache-web-service
spec:
  type: LoadBalancer
  selector:
    app: apache-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
