name: Deploy to GKE via Bastion

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: ax-non-prd
  GKE_CLUSTER_NAME: ax-data-processing
  GKE_CLUSTER_REGION: europe-west1
  GKE_NAMESPACE: prefect-preprd
  BASTION_USER: ext_mangeshv_zignuts_com
  BASTION_NAME: bastion-host-ax-non-prd
  BASTION_ZONE: europe-west1-b

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Set up gcloud CLI
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           project_id: ${{ env.PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true

#       - name: Deploy via Bastion IAP
#         run: |
#           echo "Deploying via Bastion through IAP..."

#           # Write service account key to a temporary file for the bastion
#           echo '${{ secrets.GCP_SA_KEY }}' > sa-key.json

#           # Copy the key to the bastion
#           gcloud compute scp sa-key.json $BASTION_USER@$BASTION_NAME:~/sa-key.json \
#             --project $PROJECT_ID \
#             --zone $BASTION_ZONE \
#             --tunnel-through-iap

#           # Run commands on the bastion
#           gcloud compute ssh $BASTION_USER@$BASTION_NAME \
#             --project $PROJECT_ID \
#             --zone $BASTION_ZONE \
#             --tunnel-through-iap \
#             --command "
#               echo 'Activating service account...';
#               gcloud auth activate-service-account --key-file=~/sa-key.json;

#               echo 'Getting GKE credentials...';
#               gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GKE_CLUSTER_REGION --project $PROJECT_ID;

#               echo 'Deploying hello world app...';
#               kubectl apply -f k8s/hello-world.yaml -n $GKE_NAMESPACE;

#               echo 'Cleaning up...';
#               rm ~/sa-key.json;

#               echo 'Deployment finished!';
#             "
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          version: 'latest'

      - name: Generate SSH key for gcloud
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -f ~/.ssh/google_compute_engine -N "" -q

      - name: Deploy via Bastion IAP
        run: |
          # Copy the service account key to the bastion
          echo '${{ secrets.GCP_SA_KEY }}' > sa-key.json
          gcloud compute scp sa-key.json $BASTION_USER@$BASTION_NAME:~/sa-key.json \
            --project $PROJECT_ID \
            --zone $BASTION_ZONE \
            --tunnel-through-iap

          # Run deployment commands on bastion
          gcloud compute ssh $BASTION_USER@$BASTION_NAME \
            --project $PROJECT_ID \
            --zone $BASTION_ZONE \
            --tunnel-through-iap \
            --command "
              gcloud auth activate-service-account --key-file=~/sa-key.json;
              gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GKE_CLUSTER_REGION --project $PROJECT_ID;
              kubectl apply -f k8s/hello-world.yaml -n $GKE_NAMESPACE;
              rm ~/sa-key.json;
            "
