name: Deploy to GKE via Bastion

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: ax-non-prd
  GKE_CLUSTER_NAME: ax-data-processing
  GKE_CLUSTER_REGION: europe-west1
  GKE_NAMESPACE: prefect-preprd
  GKE_PREFECT_SERVER_NAME: prefect-preprd-server
  BASTION_USER: ext_mangeshv_zignuts_com
  BASTION_NAME: bastion-host-ax-non-prd
  BASTION_ZONE: europe-west1-b

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate and deploy via Bastion IAP
        run: |
          echo "Deploying via Bastion through IAP..."

          # Use gcloud SSH with IAP to execute commands on bastion
          gcloud compute ssh $BASTION_USER@$BASTION_NAME \
            --project $PROJECT_ID \
            --zone $BASTION_ZONE \
            --tunnel-through-iap \
            --command "
              echo 'Authenticating with GKE...';
              gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GKE_CLUSTER_REGION --project $PROJECT_ID;
              
              echo 'Deploying hello world app...';
              kubectl apply -f k8s/hello-world.yaml -n $GKE_NAMESPACE;

              echo 'Deployment finished!';
            "
