name: Deploy to GKE via Connect Gateway

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: ax-non-prd
  GKE_CLUSTER_NAME: ax-data-processing
  GKE_CLUSTER_REGION: europe-west1
  GKE_NAMESPACE: prefect-preprd
  MEMBERSHIP_NAME: ax-data-processing   # fleet membership name



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud with GKE auth plugin
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Fetch kubeconfig using Connect Gateway
        run: |
          echo "Fetching kubeconfig..."
          gcloud container fleet memberships get-credentials $MEMBERSHIP_NAME \
            --project $PROJECT_ID

      - name: Verify cluster access
        run: |
          kubectl get nodes || true
          kubectl get ns

      - name: Deploy workload to Autopilot cluster
        run: |
          echo "Deploying hello world app to $GKE_NAMESPACE..."
          kubectl apply -f k8s/apache.yaml -n $GKE_NAMESPACE

          echo "Deployment finished!"
