# name: Hello World CI/CD

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# env:
#   PROJECT_ID: ax-non-prd
#   IMAGE_BASE: europe-west1-docker.pkg.dev/ax-non-prd/axium-services/hello-world
#   PREFECT_API_URL: https://test-preprd-prefect.axiumai.io/api
#   DEPLOY_PREFECT: true
#   GKE_NAMESPACE: prefect-preprd

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Authenticate GCP
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Docker Auth
#         run: |
#           gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

#       - name: Build & Push Docker
#         run: |
#           IMAGE_TAG=${{ env.IMAGE_BASE }}:latest
#           docker build -t $IMAGE_TAG .
#           docker push $IMAGE_TAG
#           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

#   deploy-gke:
#     needs: build-and-push
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Authenticate GCP
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Setup gcloud
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           project_id: ${{ env.PROJECT_ID }}
#           install_components: 'gke-gcloud-auth-plugin'
#           export_default_credentials: true

#       - name: Fetch kubeconfig
#         run: gcloud container fleet memberships get-credentials ax-data-processing --project ${{ env.PROJECT_ID }}

#       - name: Apply Kubernetes YAML
#         run: kubectl apply -f k8s/hello-world.yaml -n $GKE_NAMESPACE

#   deploy-prefect:
#     needs: build-and-push
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.12'

#       - name: Install dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y jq curl
#           pip install --upgrade pip
#           pip install prefect requests

#       - name: Get IAP Token
#         id: iap
#         run: |
#           IAP_BEARER=$(curl -s -X POST \
#             -d "client_id=${{ secrets.IAP_CLIENT_ID }}" \
#             -d "client_secret=${{ secrets.IAP_CLIENT_SECRET }}" \
#             -d "grant_type=client_credentials" \
#             -d "audience=${{ env.PREFECT_API_URL }}" \
#             https://oauth2.googleapis.com/token | jq -r .access_token)

#           if [ -z "$IAP_BEARER" ] || [ "$IAP_BEARER" = "null" ]; then
#             echo "ERROR: Failed to fetch IAP token"
#             exit 1
#           fi

#           echo "IAP_BEARER=$IAP_BEARER" >> $GITHUB_ENV
#           echo "Successfully fetched IAP token"

#       - name: Deploy Prefect Flow
#         run: ./deploy_prefect.sh dev
#         env:
#           DEPLOY_PREFECT: true
#           PREFECT_API_BEARER: ${{ env.IAP_BEARER }}
#           PREFECT_API_URL: ${{ env.PREFECT_API_URL }}

name: Hello World CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ax-non-prd
  IMAGE_BASE: europe-west1-docker.pkg.dev/ax-non-prd/axium-services/hello-world
  PREFECT_API_URL: https://test-preprd-prefect.axiumai.io/api
  DEPLOY_PREFECT: true
  GKE_NAMESPACE: prefect-preprd

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Docker Auth
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build & Push Docker
        run: |
          IMAGE_TAG=${{ env.IMAGE_BASE }}:latest
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  deploy-gke:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Fetch kubeconfig
        run: gcloud container fleet memberships get-credentials ax-data-processing --project ${{ env.PROJECT_ID }}

      - name: Apply Kubernetes YAML
        run: kubectl apply -f k8s/hello-world.yaml -n $GKE_NAMESPACE

  deploy-prefect:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          pip install --upgrade pip
          pip install prefect requests

      - name: Authenticate GCP and get IAP token
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          token_format: 'access_token'

      - name: Get IAP Identity Token
        run: |
          IAP_BEARER=$(gcloud auth print-identity-token --audiences=/projects/884212667979/iap_web/2810333306836467958)
          if [ -z "$IAP_BEARER" ]; then
            echo "ERROR: Failed to fetch IAP token"
            exit 1
          fi
          echo "IAP_BEARER=$IAP_BEARER" >> $GITHUB_ENV
          echo "Successfully fetched IAP token"

      - name: Deploy Prefect Flow
        run: ./deploy_prefect.sh dev
        env:
          DEPLOY_PREFECT: true
          PREFECT_API_BEARER: ${{ env.IAP_BEARER }}
          PREFECT_API_URL: ${{ env.PREFECT_API_URL }}


############################################
############################################



# name: Hello World CI/CD

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# env:
#   PROJECT_ID: ax-non-prd
#   IMAGE_BASE: europe-west1-docker.pkg.dev/ax-non-prd/axium-services/hello-world
#   PREFECT_API_URL: https://test-preprd-prefect.axiumai.io/api
#   DEPLOY_PREFECT: true
#   GKE_NAMESPACE: prefect-preprd

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Authenticate GCP
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Docker Auth
#         run: |
#           gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

#       - name: Build & Push Docker
#         run: |
#           IMAGE_TAG=${{ env.IMAGE_BASE }}:latest
#           docker build -t $IMAGE_TAG .
#           docker push $IMAGE_TAG
#           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

#   deploy-gke:
#     needs: build-and-push
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Authenticate GCP
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Setup gcloud
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           project_id: ${{ env.PROJECT_ID }}
#           install_components: 'gke-gcloud-auth-plugin'
#           export_default_credentials: true

#       - name: Fetch kubeconfig
#         run: gcloud container fleet memberships get-credentials ax-data-processing --project ${{ env.PROJECT_ID }}

#       - name: Apply Kubernetes YAML
#         run: kubectl apply -f k8s/hello-world.yaml -n $GKE_NAMESPACE

#   deploy-prefect:
#     needs: build-and-push
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.12'

#       - name: Install dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y jq curl
#           pip install --upgrade pip
#           pip install prefect requests google-cloud-secret-manager

#       - name: Get IAP Token
#         id: iap
#         run: |
          
#           printf "%s" "${{ secrets.GCP_SA_KEY }}" > sa-key.json
#           IAP_BEARER=$(gcloud auth activate-service-account --key-file=sa-key.json \
#                         && gcloud auth print-identity-token --audiences=/projects/884212667979/iap_web/2810333306836467958)
#           if [ -z "$IAP_BEARER" ]; then
#             echo "ERROR: Failed to fetch IAP token"
#             exit 1
#           fi
#           echo "IAP_BEARER=$IAP_BEARER" >> $GITHUB_ENV
#           echo "Successfully fetched IAP token_"

#       - name: Deploy Prefect Flow
#         run: ./deploy_prefect.sh dev
#         env:
#           DEPLOY_PREFECT: true
#           PREFECT_API_BEARER: ${{ env.IAP_BEARER }}
#           PREFECT_API_URL: ${{ env.PREFECT_API_URL }}
