jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          version: 'latest'

      - name: Generate SSH key for gcloud
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -f ~/.ssh/google_compute_engine -N "" -q

      - name: Deploy via Bastion IAP
        run: |
          # Copy the service account key to the bastion
          echo '${{ secrets.GCP_SA_KEY }}' > sa-key.json
          gcloud compute scp sa-key.json $BASTION_USER@$BASTION_NAME:~/sa-key.json \
            --project $PROJECT_ID \
            --zone $BASTION_ZONE \
            --tunnel-through-iap

          # Run deployment commands on bastion
          gcloud compute ssh $BASTION_USER@$BASTION_NAME \
            --project $PROJECT_ID \
            --zone $BASTION_ZONE \
            --tunnel-through-iap \
            --command "
              gcloud auth activate-service-account --key-file=~/sa-key.json;
              gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GKE_CLUSTER_REGION --project $PROJECT_ID;
              kubectl apply -f k8s/hello-world.yaml -n $GKE_NAMESPACE;
              rm ~/sa-key.json;
            "
